[app_servers]
app-server1 ansible_host=192.168.159.133 ansible_user=administrateur  # Remplacez par votre IP et utilisateur

[app_servers:vars]
ansible_python_interpreter=/usr/bin/python3
deploy_dir=/opt/myapp
repo_url=https://github.com/Modou255/myapp.git
node_version=16.x  # Version de Node.js requise

[jenkins]
jenkins-server ansible_host=192.168.159.133 ansible_user=administrateur  # IP de votre serveur Jenkins
